# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from msgsrv_basic_p/RobotStatus.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class RobotStatus(genpy.Message):
  _md5sum = "26fb00c2a9a55416e3fc28ca9efe50fa"
  _type = "msgsrv_basic_p/RobotStatus"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int16 motor1_rpm
int16 motor2_rpm
int16 motor3_rpm
int16 motor4_rpm
geometry_msgs/Vector3 location

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z"""
  __slots__ = ['motor1_rpm','motor2_rpm','motor3_rpm','motor4_rpm','location']
  _slot_types = ['int16','int16','int16','int16','geometry_msgs/Vector3']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       motor1_rpm,motor2_rpm,motor3_rpm,motor4_rpm,location

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(RobotStatus, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.motor1_rpm is None:
        self.motor1_rpm = 0
      if self.motor2_rpm is None:
        self.motor2_rpm = 0
      if self.motor3_rpm is None:
        self.motor3_rpm = 0
      if self.motor4_rpm is None:
        self.motor4_rpm = 0
      if self.location is None:
        self.location = geometry_msgs.msg.Vector3()
    else:
      self.motor1_rpm = 0
      self.motor2_rpm = 0
      self.motor3_rpm = 0
      self.motor4_rpm = 0
      self.location = geometry_msgs.msg.Vector3()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4h3d().pack(_x.motor1_rpm, _x.motor2_rpm, _x.motor3_rpm, _x.motor4_rpm, _x.location.x, _x.location.y, _x.location.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.location is None:
        self.location = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 32
      (_x.motor1_rpm, _x.motor2_rpm, _x.motor3_rpm, _x.motor4_rpm, _x.location.x, _x.location.y, _x.location.z,) = _get_struct_4h3d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4h3d().pack(_x.motor1_rpm, _x.motor2_rpm, _x.motor3_rpm, _x.motor4_rpm, _x.location.x, _x.location.y, _x.location.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.location is None:
        self.location = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 32
      (_x.motor1_rpm, _x.motor2_rpm, _x.motor3_rpm, _x.motor4_rpm, _x.location.x, _x.location.y, _x.location.z,) = _get_struct_4h3d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4h3d = None
def _get_struct_4h3d():
    global _struct_4h3d
    if _struct_4h3d is None:
        _struct_4h3d = struct.Struct("<4h3d")
    return _struct_4h3d
