// Generated by gencpp from file msgsrv_basic_p/WarningStatusRequest.msg
// DO NOT EDIT!


#ifndef MSGSRV_BASIC_P_MESSAGE_WARNINGSTATUSREQUEST_H
#define MSGSRV_BASIC_P_MESSAGE_WARNINGSTATUSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace msgsrv_basic_p
{
template <class ContainerAllocator>
struct WarningStatusRequest_
{
  typedef WarningStatusRequest_<ContainerAllocator> Type;

  WarningStatusRequest_()
    : warn(false)  {
    }
  WarningStatusRequest_(const ContainerAllocator& _alloc)
    : warn(false)  {
  (void)_alloc;
    }



   typedef uint8_t _warn_type;
  _warn_type warn;





  typedef boost::shared_ptr< ::msgsrv_basic_p::WarningStatusRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::msgsrv_basic_p::WarningStatusRequest_<ContainerAllocator> const> ConstPtr;

}; // struct WarningStatusRequest_

typedef ::msgsrv_basic_p::WarningStatusRequest_<std::allocator<void> > WarningStatusRequest;

typedef boost::shared_ptr< ::msgsrv_basic_p::WarningStatusRequest > WarningStatusRequestPtr;
typedef boost::shared_ptr< ::msgsrv_basic_p::WarningStatusRequest const> WarningStatusRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::msgsrv_basic_p::WarningStatusRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::msgsrv_basic_p::WarningStatusRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::msgsrv_basic_p::WarningStatusRequest_<ContainerAllocator1> & lhs, const ::msgsrv_basic_p::WarningStatusRequest_<ContainerAllocator2> & rhs)
{
  return lhs.warn == rhs.warn;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::msgsrv_basic_p::WarningStatusRequest_<ContainerAllocator1> & lhs, const ::msgsrv_basic_p::WarningStatusRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace msgsrv_basic_p

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::msgsrv_basic_p::WarningStatusRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msgsrv_basic_p::WarningStatusRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msgsrv_basic_p::WarningStatusRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msgsrv_basic_p::WarningStatusRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msgsrv_basic_p::WarningStatusRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msgsrv_basic_p::WarningStatusRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::msgsrv_basic_p::WarningStatusRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c9b6461af4510efa7832370186740da3";
  }

  static const char* value(const ::msgsrv_basic_p::WarningStatusRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc9b6461af4510efaULL;
  static const uint64_t static_value2 = 0x7832370186740da3ULL;
};

template<class ContainerAllocator>
struct DataType< ::msgsrv_basic_p::WarningStatusRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "msgsrv_basic_p/WarningStatusRequest";
  }

  static const char* value(const ::msgsrv_basic_p::WarningStatusRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::msgsrv_basic_p::WarningStatusRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool warn\n"
;
  }

  static const char* value(const ::msgsrv_basic_p::WarningStatusRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::msgsrv_basic_p::WarningStatusRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.warn);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WarningStatusRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::msgsrv_basic_p::WarningStatusRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::msgsrv_basic_p::WarningStatusRequest_<ContainerAllocator>& v)
  {
    s << indent << "warn: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.warn);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSGSRV_BASIC_P_MESSAGE_WARNINGSTATUSREQUEST_H
