// Generated by gencpp from file msgsrv_basic_p/WarningStatus.msg
// DO NOT EDIT!


#ifndef MSGSRV_BASIC_P_MESSAGE_WARNINGSTATUS_H
#define MSGSRV_BASIC_P_MESSAGE_WARNINGSTATUS_H

#include <ros/service_traits.h>


#include <msgsrv_basic_p/WarningStatusRequest.h>
#include <msgsrv_basic_p/WarningStatusResponse.h>


namespace msgsrv_basic_p
{

struct WarningStatus
{

typedef WarningStatusRequest Request;
typedef WarningStatusResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct WarningStatus
} // namespace msgsrv_basic_p


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::msgsrv_basic_p::WarningStatus > {
  static const char* value()
  {
    return "e30b85c266ffbe42abf942f98a5b4797";
  }

  static const char* value(const ::msgsrv_basic_p::WarningStatus&) { return value(); }
};

template<>
struct DataType< ::msgsrv_basic_p::WarningStatus > {
  static const char* value()
  {
    return "msgsrv_basic_p/WarningStatus";
  }

  static const char* value(const ::msgsrv_basic_p::WarningStatus&) { return value(); }
};


// service_traits::MD5Sum< ::msgsrv_basic_p::WarningStatusRequest> should match
// service_traits::MD5Sum< ::msgsrv_basic_p::WarningStatus >
template<>
struct MD5Sum< ::msgsrv_basic_p::WarningStatusRequest>
{
  static const char* value()
  {
    return MD5Sum< ::msgsrv_basic_p::WarningStatus >::value();
  }
  static const char* value(const ::msgsrv_basic_p::WarningStatusRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::msgsrv_basic_p::WarningStatusRequest> should match
// service_traits::DataType< ::msgsrv_basic_p::WarningStatus >
template<>
struct DataType< ::msgsrv_basic_p::WarningStatusRequest>
{
  static const char* value()
  {
    return DataType< ::msgsrv_basic_p::WarningStatus >::value();
  }
  static const char* value(const ::msgsrv_basic_p::WarningStatusRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::msgsrv_basic_p::WarningStatusResponse> should match
// service_traits::MD5Sum< ::msgsrv_basic_p::WarningStatus >
template<>
struct MD5Sum< ::msgsrv_basic_p::WarningStatusResponse>
{
  static const char* value()
  {
    return MD5Sum< ::msgsrv_basic_p::WarningStatus >::value();
  }
  static const char* value(const ::msgsrv_basic_p::WarningStatusResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::msgsrv_basic_p::WarningStatusResponse> should match
// service_traits::DataType< ::msgsrv_basic_p::WarningStatus >
template<>
struct DataType< ::msgsrv_basic_p::WarningStatusResponse>
{
  static const char* value()
  {
    return DataType< ::msgsrv_basic_p::WarningStatus >::value();
  }
  static const char* value(const ::msgsrv_basic_p::WarningStatusResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MSGSRV_BASIC_P_MESSAGE_WARNINGSTATUS_H
